name: minigame
version: '${version}'

main: org.nanii.minigame.Minigame
api-version: '26.1.2'
load: POSTWORLD
depend: [ Multiverse-Core ]
commands:
  arena:
permissions:
  minigame.admin:
    description: Permite crear y romper carteles de The Towers
    default: op